# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livox_detections.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16livox_detections.proto\"\xb8\x01\n\x12LidarDetectionList\x12\x1b\n\x13sensor_timestamp_us\x18\x01 \x01(\x03\x12\x1b\n\x13system_timestamp_us\x18\x02 \x01(\x03\x12%\n\x1dsystem_timestamp_detection_us\x18\x03 \x01(\x03\x12\x16\n\x0enum_detections\x18\x04 \x01(\x05\x12)\n\x10lidar_detections\x18\x05 \x03(\x0b\x32\x0f.LidarDetection\"\xd3\x01\n\x0eLidarDetection\x12\x16\n\x0ex_coordinate_m\x18\x01 \x01(\x02\x12\x16\n\x0ey_coordinate_m\x18\x02 \x01(\x02\x12\x16\n\x0ez_coordinate_m\x18\x03 \x01(\x02\x12\x10\n\x08height_m\x18\x04 \x01(\x02\x12\x0f\n\x07size_m2\x18\x05 \x01(\x02\x12\x14\n\x0c\x61spect_ratio\x18\x06 \x01(\x02\x12\x17\n\x0forientation_deg\x18\x07 \x01(\x02\x12\x13\n\x0breflectance\x18\x08 \x01(\x05\x12\x12\n\nnum_points\x18\t \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'livox_detections_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LIDARDETECTIONLIST']._serialized_start=27
  _globals['_LIDARDETECTIONLIST']._serialized_end=211
  _globals['_LIDARDETECTION']._serialized_start=214
  _globals['_LIDARDETECTION']._serialized_end=425
# @@protoc_insertion_point(module_scope)
